import { NextResponse } from "next/server";

import { createAdminClient } from "@/lib/supabase/admin";
import {
    getTelegramWebhookSecret,
    sendTelegramMessage,
} from "@/lib/telegram";

type BotType = "client" | "craftsman";

const VALID_BOT_TYPES: BotType[] = [
    "client",
    "craftsman",
];

function isBotType(value: string): value is BotType {
    return VALID_BOT_TYPES.includes(value as BotType);
}

type TelegramChat = {
    id: number;
    username?: string;
    first_name?: string;
};

type TelegramMessage = {
    chat?: TelegramChat;
    text?: string;
};

type TelegramUpdate = {
    message?: TelegramMessage;
};

export async function POST(
    request: Request,
    context: {
        params: Promise<{
            bot: string;
        }>;
    }
) {
    try {
        const { bot } = await context.params;

        if (!isBotType(bot)) {
            return NextResponse.json(
                {
                    error: "Invalid bot",
                },
                { status: 404 }
            );
        }

        /*
         * Verify that this request actually came from
         * Telegram using the secret configured when
         * the webhook was registered.
         */
        const expectedSecret =
            getTelegramWebhookSecret(bot);

        const receivedSecret = request.headers.get(
            "x-telegram-bot-api-secret-token"
        );

        if (
            !receivedSecret ||
            receivedSecret !== expectedSecret
        ) {
            return NextResponse.json(
                {
                    error: "Unauthorized",
                },
                { status: 401 }
            );
        }

        const update =
            (await request.json()) as TelegramUpdate;

        const message = update.message;

        /*
         * Ignore updates that aren't normal text messages.
         */
        if (!message?.text || !message.chat) {
            return NextResponse.json({
                ok: true,
            });
        }

        const text = message.text.trim();

        /*
         * We only care about /start for account linking.
         */
        if (!text.startsWith("/start")) {
            return NextResponse.json({
                ok: true,
            });
        }

        const parts = text.split(/\s+/);
        const token = parts[1];

        /*
         * User opened the bot directly instead of using
         * the connection link generated by Sanay3y.
         */
        if (!token) {
            await sendTelegramMessage({
                botType: bot,
                chatId: message.chat.id,
                text:
                    bot === "client"
                        ? "أهلاً بيك في صنايعي.كوم.\n\nافتح رابط ربط تيليجرام من حسابك على الموقع علشان تربط الحساب."
                        : "أهلاً بيك في صنايعي.كوم.\n\nافتح رابط ربط تيليجرام من حسابك على الموقع علشان تربط حسابك كصنايعي.",
            });

            return NextResponse.json({
                ok: true,
            });
        }

        const admin = createAdminClient();

        /*
         * Find the temporary connection token.
         */
        const { data: linkToken, error: tokenError } =
            await admin
                .from("telegram_link_tokens")
                .select(
                    "id, user_id, bot_type, expires_at"
                )
                .eq("token", token)
                .eq("bot_type", bot)
                .gt(
                    "expires_at",
                    new Date().toISOString()
                )
                .maybeSingle();

        if (tokenError) {
            console.error(
                "Telegram token lookup failed:",
                tokenError
            );

            return NextResponse.json(
                {
                    error: "Database error",
                },
                { status: 500 }
            );
        }

        /*
         * Token doesn't exist or has expired.
         */
        if (!linkToken) {
            await sendTelegramMessage({
                botType: bot,
                chatId: message.chat.id,
                text:
                    "الرابط ده غير صالح أو انتهت صلاحيته.\n\nارجع لموقع صنايعي.كوم واعمل ربط جديد.",
            });

            return NextResponse.json({
                ok: true,
            });
        }

        /*
         * Save the Telegram connection.
         *
         * The unique constraint on (user_id, bot_type)
         * makes this safe if the user reconnects.
         */
        const { error: connectionError } =
            await admin
                .from("telegram_connections")
                .upsert(
                    {
                        user_id: linkToken.user_id,
                        bot_type: bot,
                        telegram_chat_id:
                            message.chat.id,
                        telegram_username:
                            message.chat.username ?? null,
                        telegram_first_name:
                            message.chat.first_name ?? null,
                        is_active: true,
                        updated_at:
                            new Date().toISOString(),
                    },
                    {
                        onConflict:
                            "user_id,bot_type",
                    }
                );

        if (connectionError) {
            console.error(
                "Failed to save Telegram connection:",
                connectionError
            );

            return NextResponse.json(
                {
                    error:
                        "Failed to save Telegram connection",
                },
                { status: 500 }
            );
        }

        /*
         * The token is one-time use.
         */
        const { error: deleteError } =
            await admin
                .from("telegram_link_tokens")
                .delete()
                .eq("id", linkToken.id);

        if (deleteError) {
            /*
             * The connection itself already succeeded,
             * so don't fail the Telegram request.
             */
            console.error(
                "Failed to delete Telegram link token:",
                deleteError
            );
        }

        /*
         * Tell the user that the account is connected.
         */
        await sendTelegramMessage({
            botType: bot,
            chatId: message.chat.id,
            text:
                bot === "client"
                    ? "تم ربط حسابك على صنايعي.كوم بنجاح.\n\nهنبعتلك هنا إشعارات الشغل والطلبات المهمة."
                    : "تم ربط حسابك على صنايعي.كوم بنجاح.\n\nهنبعتلك هنا إشعارات الشغل والعروض المهمة.",
        });

        return NextResponse.json({
            ok: true,
        });
    } catch (error) {
        console.error(
            "Telegram webhook error:",
            error
        );

        return NextResponse.json(
            {
                error: "Internal server error",
            },
            { status: 500 }
        );
    }
}